# Copyright 2026 Internal Security Programme
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
"""Monthly forensic and compliance report (P3-4, US-8.1, BRD FR-8).

Assembly rather than new analysis: each module has carried its own report
method since it was built — ``latest_scan_summary``, ``verify_chain``,
``clone_detection_report``, ``independence_report`` and the rest. This module
calls them and renders the result. Recomputing any of it here would create two
sources of truth for the same question, and they would eventually disagree.

Two things about the design are deliberate and worth defending.

**The report leads with what is not working.** The BRD asks for an override log,
a declaration reconciliation, an anomaly summary and SoD status. All of that is
here. But a compliance report that lists activity while omitting that, say, no
high-value threshold has ever been configured, or that the audit chain broke
three weeks ago, tells the CEO/Owner the opposite of the truth: it looks like
assurance. So every section can contribute **findings**, and findings appear
first.

**A section that fails to collect becomes a finding, not a blank.** If the SoD
query raises, the report says the SoD status could not be established. A silently
empty section reads as "nothing to report", which is exactly wrong.
"""

import json
import logging
from datetime import date

from dateutil.relativedelta import relativedelta

from odoo import _, api, fields, models
from odoo.exceptions import UserError

_logger = logging.getLogger(__name__)


class ForensicReport(models.Model):
    _name = "forensic.report"
    _description = "Monthly Forensic and Compliance Report"
    _order = "period_start desc, version desc"

    name = fields.Char(string="Reference", required=True, readonly=True, copy=False)
    period_start = fields.Date(string="Period Start", required=True, readonly=True)
    period_end = fields.Date(string="Period End", required=True, readonly=True)
    version = fields.Integer(
        string="Version",
        default=1,
        required=True,
        readonly=True,
        help="Regenerating a period produces a new version rather than "
        "overwriting the previous one (US-8.1). P3-5 enforces this.",
    )
    generated_at = fields.Datetime(string="Generated At (UTC)", readonly=True)
    generated_by_id = fields.Many2one(
        comodel_name="res.users", string="Generated By", readonly=True,
        ondelete="restrict",
    )
    state = fields.Selection(
        selection=[("draft", "Draft"), ("generated", "Generated")],
        default="draft",
        required=True,
        readonly=True,
    )
    payload_json = fields.Text(string="Collected Data", readonly=True)

    # Headline figures, stored so the list view and any dashboard can read them
    # without parsing the payload.
    override_count = fields.Integer(string="Overrides Executed", readonly=True)
    override_oral_count = fields.Integer(
        string="From Oral Instruction", readonly=True,
        help="BRD FR-4.4 requires the instruction source on every override. A "
        "rising proportion here is the pattern the whole initiative exists to "
        "surface.",
    )
    anomaly_count = fields.Integer(string="Anomalies Raised", readonly=True)
    anomaly_open_high = fields.Integer(
        string="Open High/Critical", readonly=True
    )
    sod_conflict_count = fields.Integer(string="Open SoD Conflicts", readonly=True)
    declaration_outstanding = fields.Integer(
        string="Declarations Outstanding", readonly=True
    )
    chain_intact = fields.Boolean(string="Audit Chain Intact", readonly=True)
    finding_count = fields.Integer(string="Control Findings", readonly=True)
    findings_text = fields.Text(string="Findings", readonly=True)

    _sql_constraints = [
        (
            "period_version_uniq",
            "unique(period_start, period_end, version)",
            "That report version already exists for the period.",
        ),
    ]

    # ------------------------------------------------------------------
    # Collection
    # ------------------------------------------------------------------
    def _safe(self, label, func, findings):
        """Run one collector; turn a failure into a finding, never a blank."""
        try:
            return func()
        except Exception as exc:  # noqa: BLE001 - reported, not swallowed
            _logger.exception("Forensic report section failed: %s", label)
            findings.append(
                _(
                    "%(label)s could not be established: %(error)s. Treat this "
                    "section as unknown, not as clear.",
                    label=label,
                    error=exc,
                )
            )
            return {"error": str(exc), "available": False}

    def _collect_overrides(self, findings):
        """Every override in the period, with its instruction source."""
        if "override.request" not in self.env:
            return {"available": False}
        Override = self.env["override.request"].sudo()
        records = Override.search(
            [
                ("submitted_at", ">=", fields.Datetime.to_datetime(self.period_start)),
                ("submitted_at", "<=", fields.Datetime.to_datetime(self.period_end)),
            ]
        )
        rows = []
        for record in records:
            approvals = record.approval_ids.filtered(
                lambda a: a.decision == "approve"
            )
            rows.append({
                "reference": record.name,
                "target": record.target_display,
                "requester": record.requester_id.login,
                "category": record.reason_category_id.name,
                "instruction_type": record.instruction_type,
                "documented": bool(record.attachment_ids),
                "state": record.state,
                "submitted_at": str(record.submitted_at or ""),
                "executed_at": str(record.executed_at or ""),
                "approvers": approvals.mapped("approver_id.login"),
                "all_webauthn_confirmed": record.all_approvals_strong,
                "high_risk": record.high_risk,
            })
        oral = [r for r in rows if r["instruction_type"] == "oral"]
        undocumented = [r for r in rows if not r["documented"]]
        if undocumented:
            findings.append(
                _(
                    "%(count)s override(s) in the period carry no supporting "
                    "documentation.",
                    count=len(undocumented),
                )
            )
        weak = [r for r in rows if r["approvers"] and not r["all_webauthn_confirmed"]]
        if weak:
            findings.append(
                _(
                    "%(count)s override(s) include an approval that was not "
                    "cryptographically confirmed. Those approvals do not meet "
                    "BRD FR-5.3.",
                    count=len(weak),
                )
            )
        return {
            "available": True,
            "total": len(rows),
            "oral": len(oral),
            "written": len(rows) - len(oral),
            "executed": len([r for r in rows if r["state"] == "executed"]),
            "rejected": len([r for r in rows if r["state"] == "rejected"]),
            "rows": rows,
        }

    def _collect_declarations(self, findings):
        """Reconcile who has accepted the current declaration (BRD FR-8)."""
        if "declaration.version" not in self.env:
            return {"available": False}
        Version = self.env["declaration.version"].sudo()
        current = Version.get_current_version()
        if not current:
            findings.append(
                _(
                    "No declaration version is published, so no user has "
                    "accepted anything. The declaration gateway is inactive."
                )
            )
            return {"available": True, "published": False, "outstanding": 0}
        users = self.env["res.users"].sudo().search(
            [("active", "=", True), ("share", "=", False)]
        )
        outstanding = [
            u.login for u in users
            if u.must_accept_declaration and not u._is_declaration_exempt()
        ]
        mismatched = current.signoff_ids.filtered(
            lambda s: not s.hash_matches_version
        )
        if outstanding:
            findings.append(
                _(
                    "%(count)s active user(s) have not accepted the current "
                    "declaration.",
                    count=len(outstanding),
                )
            )
        if mismatched:
            findings.append(
                _(
                    "%(count)s sign-off(s) no longer match the declaration text "
                    "they were recorded against. This should be impossible and "
                    "warrants investigation.",
                    count=len(mismatched),
                )
            )
        return {
            "available": True,
            "published": True,
            "version": current.version,
            "text_hash": current.text_hash,
            "accepted": len(current.signoff_ids),
            "outstanding": len(outstanding),
            "outstanding_users": outstanding,
            "hash_mismatches": len(mismatched),
        }

    def _collect_anomalies(self, findings):
        Alert = self.env["anomaly.alert"].sudo()
        start = fields.Datetime.to_datetime(self.period_start)
        end = fields.Datetime.to_datetime(self.period_end)
        alerts = Alert.search(
            [("raised_at", ">=", start), ("raised_at", "<=", end)]
        )
        by_type, by_severity = {}, {}
        for alert in alerts:
            by_type[alert.alert_type] = by_type.get(alert.alert_type, 0) + 1
            by_severity[alert.severity] = by_severity.get(alert.severity, 0) + 1
        open_high = Alert.search_count(
            [("state", "=", "new"), ("severity", "in", ("high", "critical"))]
        )
        if open_high:
            findings.append(
                _(
                    "%(count)s high or critical anomaly alert(s) remain "
                    "unreviewed.",
                    count=open_high,
                )
            )
        review_activity = Alert.review_activity_report(days=31)
        if review_activity.get("bulk_reviews"):
            findings.append(
                _(
                    "%(count)s alert(s) were closed as part of a bulk review. "
                    "Batch dismissals receive less individual scrutiny by "
                    "definition.",
                    count=review_activity["bulk_reviews"],
                )
            )
        return {
            "available": True,
            "total": len(alerts),
            "by_type": by_type,
            "by_severity": by_severity,
            "open_high_or_critical": open_high,
            "review_activity": review_activity,
        }

    def _collect_control_health(self, findings):
        """The section that makes this a compliance report rather than a log."""
        health = {}

        if "audit.locker.entry" in self.env:
            chain = self.env["audit.locker.entry"].sudo().verify_chain(
                raise_anomaly=False
            )
            health["audit_chain"] = chain
            if not chain["intact"]:
                findings.append(
                    _(
                        "THE AUDIT CHAIN IS BROKEN at sequence %(seq)s. %(reason)s "
                        "The audit trail cannot be relied upon until this is "
                        "explained.",
                        seq=chain["first_break_sequence"],
                        reason=chain["reason"],
                    )
                )

        if "sec.freeze.rule" in self.env:
            Rule = self.env["sec.freeze.rule"].sudo()
            triggers = Rule.verify_triggers()
            health["freeze_triggers"] = triggers
            if not triggers["healthy"]:
                findings.append(
                    _(
                        "Database freeze trigger(s) missing: %(missing)s. "
                        "Frozen records on those tables can currently be "
                        "changed by direct SQL.",
                        missing=", ".join(triggers["missing"]),
                    )
                )
            inactive = Rule.search([("enforcement_active", "=", False)])
            health["freeze_rules_disabled"] = inactive.mapped("model_name")
            if inactive:
                findings.append(
                    _(
                        "Freeze enforcement is switched OFF for: %(models)s.",
                        models=", ".join(inactive.mapped("model_name")),
                    )
                )

        if "sec.stream.lock" in self.env:
            locks = self.env["sec.stream.lock"].sudo().search([("locked", "=", True)])
            health["streams_locked"] = locks.mapped("stream")
            weak_toggles = self.env["sec.stream.lock.log"].sudo().search_count(
                [("strongly_authenticated", "=", False)]
            )
            health["unconfirmed_lock_toggles"] = weak_toggles
            if weak_toggles:
                findings.append(
                    _(
                        "%(count)s back-end lock toggle(s) were made without "
                        "WebAuthn confirmation (BRD FR-3.3 expects it).",
                        count=weak_toggles,
                    )
                )

        if "sec.value.threshold" in self.env:
            coverage = self.env["sec.value.threshold"].sudo().coverage_report()
            health["value_thresholds"] = coverage
            if not coverage["any_configured"]:
                findings.append(
                    _(
                        "No high-value thresholds are configured, so no edit "
                        "was or could have been flagged on value this period."
                    )
                )

        if "sec.webauthn.credential" in self.env:
            Credential = self.env["sec.webauthn.credential"].sudo()
            enrolment = self.env["res.users"].sudo().webauthn_enrolment_report()
            clones = Credential.clone_detection_report()
            health["webauthn_enrolment"] = enrolment
            health["clone_detection"] = clones
            if not enrolment["ready"]:
                findings.append(
                    _(
                        "%(count)s approver(s) do not hold enough enrolled "
                        "authenticators. The CEO/Owner tier requires two "
                        "(BRD FR-6.5).",
                        count=len(enrolment["outstanding"]),
                    )
                )
            if not clones["clean"]:
                findings.append(
                    _(
                        "%(count)s authenticator(s) were revoked as suspected "
                        "clones.",
                        count=len(clones["clones_suspected"]),
                    )
                )
            if clones["credentials_without_clone_detection"]:
                findings.append(
                    _(
                        "%(count)s enrolled authenticator(s) report no signature "
                        "counter, so a copied key would not announce itself. "
                        "Hardware keys are the mitigation.",
                        count=len(clones["credentials_without_clone_detection"]),
                    )
                )

        if "override.request" in self.env:
            Override = self.env["override.request"].sudo()
            health["approval_strength"] = Override.approvals_without_strong_auth()
            health["independence"] = Override.independence_report()
            if not health["independence"]["clean"]:
                findings.append(
                    _("Independence signals were raised on one or more overrides.")
                )

        if "role.plaza_model" in self.env:
            readiness = self.env["role.plaza_model"].sudo().check_catalog_readiness()
            health["role_catalog"] = readiness
            for problem in readiness["findings"]:
                findings.append(_("Role catalog: %s", problem))

        return health

    def _collect_sod(self, findings):
        if "plaza.sod.scan" not in self.env:
            return {"available": False}
        Scan = self.env["plaza.sod.scan"].sudo()
        summary = Scan.latest_scan_summary()
        if not summary.get("has_scan"):
            findings.append(
                _(
                    "No segregation-of-duties scan has ever been run, so SoD "
                    "status for this period is unknown (BRD FR-2.4)."
                )
            )
        elif summary.get("open_conflicts"):
            findings.append(
                _(
                    "%(count)s open segregation-of-duties conflict(s).",
                    count=summary["open_conflicts"],
                )
            )
        return summary

    # ------------------------------------------------------------------
    # Generation
    # ------------------------------------------------------------------
    def action_generate(self):
        """Collect everything and freeze the result onto the record."""
        self.ensure_one()
        if self.state == "generated":
            raise UserError(
                _(
                    "This report has already been generated. Generate a new "
                    "version for the period rather than overwriting it."
                )
            )
        findings = []
        payload = {
            "period": {
                "start": str(self.period_start),
                "end": str(self.period_end),
            },
            "overrides": self._safe(
                _("Override log"), lambda: self._collect_overrides(findings), findings
            ),
            "declarations": self._safe(
                _("Declaration reconciliation"),
                lambda: self._collect_declarations(findings),
                findings,
            ),
            "anomalies": self._safe(
                _("Anomaly summary"), lambda: self._collect_anomalies(findings), findings
            ),
            "segregation_of_duties": self._safe(
                _("Segregation of duties"), lambda: self._collect_sod(findings), findings
            ),
            "control_health": self._safe(
                _("Control health"),
                lambda: self._collect_control_health(findings),
                findings,
            ),
        }
        payload["findings"] = findings

        overrides = payload["overrides"]
        declarations = payload["declarations"]
        anomalies = payload["anomalies"]
        sod = payload["segregation_of_duties"]
        chain = (payload["control_health"] or {}).get("audit_chain") or {}

        self.sudo().write({
            "state": "generated",
            "generated_at": fields.Datetime.now(),
            "generated_by_id": self.env.user.id,
            "payload_json": json.dumps(payload, indent=2, sort_keys=True, default=str),
            "override_count": overrides.get("total", 0) if isinstance(overrides, dict) else 0,
            "override_oral_count": overrides.get("oral", 0) if isinstance(overrides, dict) else 0,
            "anomaly_count": anomalies.get("total", 0) if isinstance(anomalies, dict) else 0,
            "anomaly_open_high": anomalies.get("open_high_or_critical", 0)
            if isinstance(anomalies, dict) else 0,
            "sod_conflict_count": sod.get("open_conflicts", 0) if isinstance(sod, dict) else 0,
            "declaration_outstanding": declarations.get("outstanding", 0)
            if isinstance(declarations, dict) else 0,
            "chain_intact": bool(chain.get("intact", False)),
            "finding_count": len(findings),
            "findings_text": "\n".join("- %s" % f for f in findings)
            or _("No control findings for this period."),
        })
        _logger.info(
            "Forensic report %s generated: %s finding(s)", self.name, len(findings)
        )
        return True

    @api.model
    def generate_for_period(self, period_start, period_end, name=None):
        """Create and generate a report for an explicit period."""
        existing = self.sudo().search(
            [("period_start", "=", period_start), ("period_end", "=", period_end)],
            order="version desc",
            limit=1,
        )
        version = (existing.version + 1) if existing else 1
        report = self.sudo().create({
            "name": name
            or _("FR/%(period)s/v%(version)s",
                 period=fields.Date.to_date(period_start).strftime("%Y-%m"),
                 version=version),
            "period_start": period_start,
            "period_end": period_end,
            "version": version,
        })
        report.action_generate()
        return report

    @api.model
    def cron_generate_monthly(self):
        """Generate last month's report. Scheduled for the 1st."""
        today = date.today()
        first_of_this_month = today.replace(day=1)
        period_start = first_of_this_month - relativedelta(months=1)
        period_end = first_of_this_month - relativedelta(days=1)
        report = self.generate_for_period(period_start, period_end)
        report._notify_owner()
        return report

    def _notify_owner(self):
        """Send the report to the Super Administrators.

        A monthly report nobody is told about is a file on a disk. The findings
        count goes in the subject so an inbox scan carries the signal.
        """
        self.ensure_one()
        group = self.env.ref(
            "sec_plaza_rbac.group_security_super_admin", raise_if_not_found=False
        )
        if not group:
            return
        for partner in group.sudo().user_ids.mapped("partner_id"):
            try:
                partner.message_post(
                    subject=_(
                        "Forensic report %(name)s — %(count)s finding(s)",
                        name=self.name,
                        count=self.finding_count,
                    ),
                    body=_(
                        "<p>Period %(start)s to %(end)s.</p>"
                        "<p>%(overrides)s override(s), %(anomalies)s anomaly "
                        "alert(s), %(findings)s control finding(s).</p>"
                        "<pre>%(text)s</pre>",
                        start=self.period_start,
                        end=self.period_end,
                        overrides=self.override_count,
                        anomalies=self.anomaly_count,
                        findings=self.finding_count,
                        text=self.findings_text,
                    ),
                )
            except Exception:  # noqa: BLE001 - notification is not the report
                _logger.exception("Could not notify %s of report", partner.name)

    def payload(self):
        """Parsed payload, for the QWeb template."""
        self.ensure_one()
        try:
            return json.loads(self.payload_json or "{}")
        except ValueError:
            return {}
